### ISSUE TITLE
RTSP stream cuts out after a few minutes

### ISSUE THREAD

**Issue by nfaliszewski** [krontech/chronos-cli#12]
When viewing the RTSP stream with VLC, after a few minutes, the stream will drop out. "Dropout" means that the stream will stop being received and VLC will stop displaying the stream. User has to press 'play' or re-open the stream to get it working again. I can't recall if this happens both when using ethernet and USB, or just one or the other. Supposedly this can be affected by increasing the incoming data buffer on VLC, but the problem with that is it can increase the delay between the camera and VLC.

**Comment by sanjpm** [comment]
Closed here: https://github.com/krontech/chronos-cli/commit/e10e8a9aeabcf22bf8c6a8596c424823d157c91c

Fixed as of Chronos 1.4 and 2.1 software version 0.7.1
